/** 可商用验收材料一键导出包（纯函数，便于单测） */

import type { ReadinessArchivePayload } from './readinessArchive.ts'
import type { OpsActionEntry } from './opsActionLog.ts'
import type { ClientBuildInfo } from './buildInfo.ts'
import type { LocaleCode } from './localizedText.ts'

export const ACCEPTANCE_PACK_KIND = 'mts.acceptance.pack' as const
export const ACCEPTANCE_PACK_VERSION = 1 as const

export interface ServerVersionInfo {
  version: string
  commit?: string
  built_at?: string
}

export interface AcceptancePackInput {
  archive: ReadinessArchivePayload
  client: ClientBuildInfo
  server?: ServerVersionInfo | null
  opsActions?: OpsActionEntry[]
  operator?: string
  note?: string
  now?: string
  /** 若省略则继承 archive.locale */
  locale?: LocaleCode
}

export interface AcceptancePackPayload {
  version: typeof ACCEPTANCE_PACK_VERSION
  kind: typeof ACCEPTANCE_PACK_KIND
  exported_at: string
  operator: string
  note: string
  locale: LocaleCode
  disclaimer: string
  client: ClientBuildInfo
  server: ServerVersionInfo | null
  readiness: ReadinessArchivePayload
  ops_actions: OpsActionEntry[]
}

const copy = {
  zh: {
    disclaimer:
      '本包由 Dashboard 就绪中心生成，用于交接与自检材料汇总，不代表生产人工验收、边缘证书或异地备份已完成。',
    title: '# MTS 可商用验收材料包',
    exportedAt: '导出时间',
    operator: '操作者',
    score: '就绪评分',
    client: '客户端',
    server: '服务端',
    serverMissing: '未加载',
    note: '备注',
    parts: '## 就绪分项',
    checklist: '清单',
    backup: '备份',
    reasons: '扣分原因',
    doctor: '## Doctor',
    notLoaded: '未加载',
    ops: '## 运维操作历史（会话）',
    empty: '（空）',
    more: '共',
    items: '条',
  },
  en: {
    disclaimer:
      'Generated by Dashboard readiness center for handoff/self-check materials; does not prove production human acceptance, edge certificates, or off-host backups are complete.',
    title: '# MTS commercial acceptance pack',
    exportedAt: 'Exported at',
    operator: 'Operator',
    score: 'Readiness score',
    client: 'Client',
    server: 'Server',
    serverMissing: 'not loaded',
    note: 'Note',
    parts: '## Readiness breakdown',
    checklist: 'Checklist',
    backup: 'Backup',
    reasons: 'Score deductions',
    doctor: '## Doctor',
    notLoaded: 'Not loaded',
    ops: '## Ops action history (session)',
    empty: '(empty)',
    more: 'total',
    items: 'entries',
  },
} as const

export function buildAcceptancePack(input: AcceptancePackInput): AcceptancePackPayload {
  const exported_at = input.now ?? new Date().toISOString()
  const locale: LocaleCode =
    input.locale === 'en' || input.locale === 'zh'
      ? input.locale
      : input.archive.locale === 'en'
        ? 'en'
        : 'zh'
  const t = copy[locale]
  const server = input.server
    ? {
        version: String(input.server.version || ''),
        commit: input.server.commit ? String(input.server.commit) : undefined,
        built_at: input.server.built_at ? String(input.server.built_at) : undefined,
      }
    : null
  return {
    version: ACCEPTANCE_PACK_VERSION,
    kind: ACCEPTANCE_PACK_KIND,
    exported_at,
    operator: (input.operator ?? input.archive.operator ?? '').trim() || 'unknown',
    note: (input.note ?? '').trim(),
    locale,
    disclaimer: t.disclaimer,
    client: { ...input.client },
    server,
    readiness: input.archive,
    ops_actions: (input.opsActions ?? []).map((x) => ({ ...x })),
  }
}

export function formatAcceptancePackMarkdown(pack: AcceptancePackPayload): string {
  const locale: LocaleCode = pack.locale === 'en' ? 'en' : 'zh'
  const t = copy[locale]
  const sep = locale === 'zh' ? '：' : ': '
  const lines: string[] = [
    t.title,
    '',
    `- ${t.exportedAt}${sep}${pack.exported_at}`,
    `- ${t.operator}${sep}${pack.operator}`,
    `- ${t.score}${sep}${pack.readiness.score.total}%`,
    `- ${t.client}${sep}${pack.client.name} ${pack.client.version} (${pack.client.mode})`,
  ]
  if (pack.server) {
    lines.push(
      `- ${t.server}${sep}${pack.server.version}${pack.server.commit ? ` @ ${pack.server.commit}` : ''}${
        pack.server.built_at ? ` · built ${pack.server.built_at}` : ''
      }`,
    )
  } else {
    lines.push(`- ${t.server}${sep}${t.serverMissing}`)
  }
  if (pack.note) lines.push(`- ${t.note}${sep}${pack.note}`)
  lines.push('', t.parts, '')
  lines.push(
    `- ${t.checklist} ${pack.readiness.score.checklist}% / HTTPS ${pack.readiness.score.edgeHttps}% / ${t.backup} ${pack.readiness.score.backupSchedule}% / Doctor ${pack.readiness.score.doctor}%`,
  )
  if (pack.readiness.score.reasons.length) {
    lines.push(`- ${t.reasons}${sep}${pack.readiness.score.reasons.join(', ')}`)
  }
  // 本地化清单标题摘要（便于英文交接）
  const sample = pack.readiness.catalog?.production?.find((x) => x.id === 'https-edge')
  if (sample?.title) {
    lines.push(`- catalog.sample: ${sample.id} — ${sample.title}`)
  }
  lines.push('', t.doctor, '')
  if (!pack.readiness.doctor.loaded) {
    lines.push(
      `- ${t.notLoaded}${pack.readiness.doctor.error ? `${sep}${pack.readiness.doctor.error}` : ''}`,
    )
  } else {
    lines.push(`- ok: ${pack.readiness.doctor.ok === true ? 'yes' : 'no'}`)
    lines.push(`- http_tls_enabled: ${String(pack.readiness.doctor.http_tls_enabled)}`)
    lines.push(`- warn_count: ${pack.readiness.doctor.warn_count ?? 0}`)
  }
  lines.push('', t.ops, '')
  if (!pack.ops_actions.length) {
    lines.push(`- ${t.empty}`)
  } else {
    for (const a of pack.ops_actions.slice(0, 20)) {
      lines.push(`- [${a.status}] ${a.kind} @ ${new Date(a.at).toISOString()}: ${a.message}`)
    }
    if (pack.ops_actions.length > 20) {
      lines.push(`- … ${t.more} ${pack.ops_actions.length} ${t.items}`)
    }
  }
  lines.push('', '---', '', `_${pack.disclaimer}_`, '')
  return lines.join('\n')
}

export function acceptancePackFilenames(at = new Date()): { json: string; md: string } {
  const stamp = at.toISOString().replace(/[:.]/g, '-').slice(0, 19)
  return {
    json: `mts-acceptance-pack-${stamp}.json`,
    md: `mts-acceptance-pack-${stamp}.md`,
  }
}
