/** 可商用验收材料一键导出包（纯函数，便于单测） */

import type { ReadinessArchivePayload } from './readinessArchive.ts'
import type { OpsActionEntry } from './opsActionLog.ts'
import type { ClientBuildInfo } from './buildInfo.ts'
import type { LocaleCode } from './localizedText.ts'
import {
  buildDeployKitSummary,
  type DeployKitSummary,
} from './deployTemplates.ts'
import {
  assessSignoffCompleteness,
  signoffFieldLabel,
  type SignoffNoteField,
} from './signoffExport.ts'
import {
  buildExportPreflight,
  type ExportPreflightItem,
} from './exportPreflight.ts'
import { formatDownsampleStatusSummaryLine } from './downsampleStatusSummary.ts'
import {
  formatPasswordPolicyHandoffLine,
  formatSessionCalibrationHandoffLine,
  formatDataContractHandoffLine,
} from './commercialHandoffSummary.ts'
import {
  toAcceptanceDataContractSummary,
  type AcceptanceDataContractSummary,
} from './dataContractView.ts'

export const ACCEPTANCE_PACK_KIND = 'mts.acceptance.pack' as const
export const ACCEPTANCE_PACK_VERSION = 2 as const

export interface ServerVersionInfo {
  version: string
  commit?: string
  built_at?: string
}

export interface AcceptancePackInput {
  archive: ReadinessArchivePayload
  client: ClientBuildInfo
  server?: ServerVersionInfo | null
  opsActions?: OpsActionEntry[]
  operator?: string
  note?: string
  now?: string
  /** 若省略则继承 archive.locale */
  locale?: LocaleCode
  /** 可选覆盖；默认按 locale 生成部署材料包摘要 */
  deployKit?: DeployKitSummary
}

export interface AcceptancePackPayload {
  version: typeof ACCEPTANCE_PACK_VERSION
  kind: typeof ACCEPTANCE_PACK_KIND
  exported_at: string
  operator: string
  note: string
  locale: LocaleCode
  disclaimer: string
  client: ClientBuildInfo
  server: ServerVersionInfo | null
  readiness: ReadinessArchivePayload
  ops_actions: OpsActionEntry[]
  /** 部署材料包索引（不含样例全文，避免验收包过大） */
  deploy_kit: DeployKitSummary
  /** 签核备注完整性（来自归档 state.signoffNotes；不计入评分） */
  signoff_completeness: {
    filled: SignoffNoteField[]
    missing: SignoffNoteField[]
    complete: boolean
    filled_count: number
    total: number
    filled_labels: string[]
    missing_labels: string[]
  }
  /** 导出前预检摘要（不计分；不代表验收完成） */
  export_preflight: {
    warn_count: number
    info_count: number
    ok_count: number
    items: Pick<ExportPreflightItem, 'id' | 'level' | 'message' | 'target'>[]
  }
  /** 数据面契约快照（顶层机器可读；与 commercial_handoff.data_contract 对齐） */
  data_contract: AcceptanceDataContractSummary
}

const copy = {
  zh: {
    disclaimer:
      '本包由 Dashboard 就绪中心生成，用于交接与自检材料汇总，不代表生产人工验收、边缘证书或异地备份已完成。',
    title: '# MTS 可商用验收材料包',
    exportedAt: '导出时间',
    operator: '操作者',
    score: '就绪评分',
    client: '客户端',
    server: '服务端',
    serverMissing: '未加载',
    note: '备注',
    parts: '## 就绪分项',
    checklist: '清单',
    backup: '备份',
    reasons: '扣分原因',
    doctor: '## Doctor',
    notLoaded: '未加载',
    ops: '## 运维操作历史（会话）',
    empty: '（空）',
    more: '共',
    items: '条',
    deployKit: '## 部署材料包索引',
    deployKitCount: '样例数',
    deployKitManual: '人工签核',
    deployKitRequired: '必做',
    deployKitDocs: '相关文档',
    signoff: '## 签核备注完整性',
    signoffFilled: '已填写',
    signoffMissing: '未填写',
    signoffComplete: '已齐',
    signoffIncomplete: '未齐',
    signoffNotScored: '不计入就绪评分，不代表验收完成',
    preflight: '## 导出前预检',
    preflightWarn: 'warn',
    preflightInfo: 'info',
    preflightOk: 'ok',
    preflightNotScored: '预检不阻止导出，不代表生产验收完成',
    dataContract: '## 数据面契约',
    dataContractLoaded: '已加载',
    dataContractMissing: '未加载',
    dataContractComplete: '能力齐全',
    dataContractIncomplete: '能力缺失',
  },
  en: {
    disclaimer:
      'Generated by Dashboard readiness center for handoff/self-check materials; does not prove production human acceptance, edge certificates, or off-host backups are complete.',
    title: '# MTS commercial acceptance pack',
    exportedAt: 'Exported at',
    operator: 'Operator',
    score: 'Readiness score',
    client: 'Client',
    server: 'Server',
    serverMissing: 'not loaded',
    note: 'Note',
    parts: '## Readiness breakdown',
    checklist: 'Checklist',
    backup: 'Backup',
    reasons: 'Score deductions',
    doctor: '## Doctor',
    notLoaded: 'Not loaded',
    ops: '## Ops action history (session)',
    empty: '(empty)',
    more: 'total',
    items: 'entries',
    deployKit: '## Deployment kit index',
    deployKitCount: 'Samples',
    deployKitManual: 'Manual sign-off',
    deployKitRequired: 'required',
    deployKitDocs: 'Related docs',
    signoff: '## Sign-off note completeness',
    signoffFilled: 'Filled',
    signoffMissing: 'Missing',
    signoffComplete: 'complete',
    signoffIncomplete: 'incomplete',
    signoffNotScored: 'Not scored; does not complete acceptance',
    preflight: '## Export preflight',
    preflightWarn: 'warn',
    preflightInfo: 'info',
    preflightOk: 'ok',
    preflightNotScored: 'Preflight does not block export or complete acceptance',
    dataContract: '## Data-plane contract',
    dataContractLoaded: 'loaded',
    dataContractMissing: 'not loaded',
    dataContractComplete: 'complete',
    dataContractIncomplete: 'incomplete',
  },
} as const

export function buildAcceptancePack(input: AcceptancePackInput): AcceptancePackPayload {
  const exported_at = input.now ?? new Date().toISOString()
  const locale: LocaleCode =
    input.locale === 'en' || input.locale === 'zh'
      ? input.locale
      : input.archive.locale === 'en'
        ? 'en'
        : 'zh'
  const t = copy[locale]
  const server = input.server
    ? {
        version: String(input.server.version || ''),
        commit: input.server.commit ? String(input.server.commit) : undefined,
        built_at: input.server.built_at ? String(input.server.built_at) : undefined,
      }
    : null
  const deploy_kit = input.deployKit ?? buildDeployKitSummary(locale)
  const sc = assessSignoffCompleteness(input.archive.signoff_notes ?? input.archive.state?.signoffNotes)
  const score = input.archive.score
  const handoffContract = input.archive.commercial_handoff?.data_contract
  const data_contract = toAcceptanceDataContractSummary(handoffContract ?? null)
  const pf = buildExportPreflight({
    locale,
    requiredChecklistRatio: (score.checklist ?? 0) / 100,
    edgeHttpsRequiredRatio: (score.edgeHttps ?? 0) / 100,
    backupScheduleRequiredRatio: (score.backupSchedule ?? 0) / 100,
    doctorLoaded: !!input.archive.doctor?.loaded,
    doctorOk: input.archive.doctor?.ok,
    doctorWarnCount: input.archive.doctor?.warn_count,
    httpTlsEnabled: input.archive.doctor?.http_tls_enabled ?? null,
    signoffNotes: input.archive.signoff_notes ?? input.archive.state?.signoffNotes,
    deployKitReviewed: !!input.archive.state?.deployKit?.reviewed,
    dataContractLoaded: data_contract.loaded,
    dataContractComplete: data_contract.complete,
    dataContractMissing: data_contract.missing_required,
  })
  return {
    version: ACCEPTANCE_PACK_VERSION,
    kind: ACCEPTANCE_PACK_KIND,
    exported_at,
    operator: (input.operator ?? input.archive.operator ?? '').trim() || 'unknown',
    note: (input.note ?? '').trim(),
    locale,
    disclaimer: t.disclaimer,
    client: { ...input.client },
    server,
    readiness: input.archive,
    ops_actions: (input.opsActions ?? []).map((x) => ({ ...x })),
    deploy_kit: {
      count: deploy_kit.count,
      manual_signoff_required: true,
      note: deploy_kit.note,
      items: deploy_kit.items.map((x) => ({ ...x })),
      docs: [...deploy_kit.docs],
    },
    signoff_completeness: {
      filled: [...sc.filled],
      missing: [...sc.missing],
      complete: sc.complete,
      filled_count: sc.filledCount,
      total: sc.total,
      filled_labels: sc.filled.map((f) => signoffFieldLabel(f, locale)),
      missing_labels: sc.missing.map((f) => signoffFieldLabel(f, locale)),
    },
    export_preflight: {
      warn_count: pf.warnCount,
      info_count: pf.infoCount,
      ok_count: pf.okCount,
      items: pf.items.map((i) => ({
        id: i.id,
        level: i.level,
        message: i.message,
        target: i.target,
      })),
    },
    data_contract,
  }
}

export function formatAcceptancePackMarkdown(pack: AcceptancePackPayload): string {
  const locale: LocaleCode = pack.locale === 'en' ? 'en' : 'zh'
  const t = copy[locale]
  const sep = locale === 'zh' ? '：' : ': '
  const lines: string[] = [
    t.title,
    '',
    `- ${t.exportedAt}${sep}${pack.exported_at}`,
    `- ${t.operator}${sep}${pack.operator}`,
    `- ${t.score}${sep}${pack.readiness.score.total}%`,
    `- ${t.client}${sep}${pack.client.name} ${pack.client.version} (${pack.client.mode})`,
  ]
  if (pack.server) {
    lines.push(
      `- ${t.server}${sep}${pack.server.version}${pack.server.commit ? ` @ ${pack.server.commit}` : ''}${
        pack.server.built_at ? ` · built ${pack.server.built_at}` : ''
      }`,
    )
  } else {
    lines.push(`- ${t.server}${sep}${t.serverMissing}`)
  }
  if (pack.note) lines.push(`- ${t.note}${sep}${pack.note}`)
  lines.push('', t.parts, '')
  lines.push(
    `- ${t.checklist} ${pack.readiness.score.checklist}% / HTTPS ${pack.readiness.score.edgeHttps}% / ${t.backup} ${pack.readiness.score.backupSchedule}% / Doctor ${pack.readiness.score.doctor}%`,
  )
  if (pack.readiness.score.reasons.length) {
    lines.push(`- ${t.reasons}${sep}${pack.readiness.score.reasons.join(', ')}`)
  }
  const sample = pack.readiness.catalog?.production?.find((x) => x.id === 'https-edge')
  if (sample?.title) {
    lines.push(`- catalog.sample: ${sample.id} — ${sample.title}`)
  }
  lines.push('', t.doctor, '')
  if (!pack.readiness.doctor.loaded) {
    lines.push(
      `- ${t.notLoaded}${pack.readiness.doctor.error ? `${sep}${pack.readiness.doctor.error}` : ''}`,
    )
  } else {
    lines.push(`- ok: ${pack.readiness.doctor.ok === true ? 'yes' : 'no'}`)
    if (pack.readiness.doctor.path) lines.push(`- path: ${pack.readiness.doctor.path}`)
    lines.push(`- http_tls_enabled: ${String(pack.readiness.doctor.http_tls_enabled)}`)
    lines.push(`- warn_count: ${pack.readiness.doctor.warn_count ?? 0}`)
  }
  if (pack.readiness.api_paths) {
    lines.push('', '## API paths', '')
    const ap = pack.readiness.api_paths
    if (ap.doctor) lines.push(`- doctor: ${ap.doctor}`)
    if (ap.version) lines.push(`- version: ${ap.version}`)
    if (ap.ops_status) lines.push(`- ops_status: ${ap.ops_status}`)
    if (ap.health) lines.push(`- health: ${ap.health}`)
    if (ap.downsample_statuses) lines.push(`- downsample_statuses: ${ap.downsample_statuses}`)
  }
  lines.push('', t.deployKit, '')
  lines.push(`- ${t.deployKitCount}${sep}${pack.deploy_kit.count}`)
  lines.push(
    `- ${t.deployKitManual}${sep}${pack.deploy_kit.manual_signoff_required ? t.deployKitRequired : 'optional'}`,
  )
  lines.push(`- ${t.note}${sep}${pack.deploy_kit.note}`)
  for (const item of pack.deploy_kit.items) {
    lines.push(`- ${item.id} — ${item.title} (\`${item.filename}\`)`)
  }
  if (pack.deploy_kit.docs.length) {
    lines.push(`- ${t.deployKitDocs}${sep}${pack.deploy_kit.docs.join(', ')}`)
  }
  lines.push('', t.signoff, '')
  lines.push(
    `- ${pack.signoff_completeness.complete ? t.signoffComplete : t.signoffIncomplete}${sep}${pack.signoff_completeness.filled_count}/${pack.signoff_completeness.total}`,
  )
  lines.push(
    `- ${t.signoffFilled}${sep}${pack.signoff_completeness.filled_labels.join(locale === 'en' ? ', ' : '、') || '—'}`,
  )
  lines.push(
    `- ${t.signoffMissing}${sep}${pack.signoff_completeness.missing_labels.join(locale === 'en' ? ', ' : '、') || '—'}`,
  )
  lines.push(`- ${t.signoffNotScored}`)
  lines.push('', t.preflight, '')
  lines.push(
    `- ${t.preflightOk}${sep}${pack.export_preflight.ok_count} · ${t.preflightWarn}${sep}${pack.export_preflight.warn_count} · ${t.preflightInfo}${sep}${pack.export_preflight.info_count}`,
  )
  for (const item of pack.export_preflight.items.filter((x) => x.level !== 'ok' || x.id === 'footer').slice(0, 12)) {
    lines.push(`- [${item.level}] ${item.id}: ${item.message}`)
  }
  lines.push(`- ${t.preflightNotScored}`)
  if (pack.readiness.downsample_status_summary) {
    lines.push('', '## Downsample status summary', '')
    lines.push(`- ${formatDownsampleStatusSummaryLine(pack.readiness.downsample_status_summary)}`)
  }
  if (pack.readiness.commercial_handoff) {
    lines.push('', '## Commercial handoff', '')
    lines.push(
      `- password_policy: ${formatPasswordPolicyHandoffLine(pack.readiness.commercial_handoff.password_policy)}`,
    )
    lines.push(
      `- session_calibration: ${formatSessionCalibrationHandoffLine(pack.readiness.commercial_handoff.session_calibration)}`,
    )
    lines.push(
      `- data_contract: ${formatDataContractHandoffLine(pack.readiness.commercial_handoff.data_contract)}`,
    )
  }
  lines.push('', t.dataContract, '')
  lines.push(
    `- status: ${pack.data_contract.loaded ? t.dataContractLoaded : t.dataContractMissing} / ${
      pack.data_contract.complete ? t.dataContractComplete : t.dataContractIncomplete
    }`,
  )
  lines.push(`- path: ${pack.data_contract.path}`)
  lines.push(`- summary: ${pack.data_contract.summary_line}`)
  if (pack.data_contract.missing_required.length) {
    lines.push(`- missing: ${pack.data_contract.missing_required.join(', ')}`)
  }
  lines.push('', t.ops, '')
  if (!pack.ops_actions.length) {
    lines.push(`- ${t.empty}`)
  } else {
    for (const a of pack.ops_actions.slice(0, 20)) {
      lines.push(`- [${a.status}] ${a.kind} @ ${new Date(a.at).toISOString()}: ${a.message}`)
    }
    if (pack.ops_actions.length > 20) {
      lines.push(`- … ${t.more} ${pack.ops_actions.length} ${t.items}`)
    }
  }
  lines.push('', '---', '', `_${pack.disclaimer}_`, '')
  return lines.join('\n')
}

export function acceptancePackFilenames(at = new Date()): { json: string; md: string } {
  const stamp = at.toISOString().replace(/[:.]/g, '-').slice(0, 19)
  return {
    json: `mts-acceptance-pack-${stamp}.json`,
    md: `mts-acceptance-pack-${stamp}.md`,
  }
}
