/** 就绪/演练归档模板（JSON + Markdown），供运维交接下载 */

import type { ReadinessScoreBreakdown } from './readinessScore.ts'
import type { ReadinessState } from './readinessState.ts'
import { completedIds } from './readinessState.ts'
import type { LocaleCode } from './localizedText.ts'
import {
  backupScheduleCatalog,
  edgeHttpsCatalog,
  productionCatalog,
  type CatalogItem,
} from './checklistCatalog.ts'

export interface DoctorArchiveSummary {
  loaded: boolean
  ok?: boolean
  http_tls_enabled?: boolean | null
  warn_count?: number
  checks?: { level: string; code: string; message: string }[]
  error?: string
}

export interface ReadinessArchiveInput {
  operator?: string
  note?: string
  state: ReadinessState
  score: ReadinessScoreBreakdown
  doctor: DoctorArchiveSummary
  now?: string
  /** 导出文案语言；默认 zh */
  locale?: LocaleCode
}

export interface ReadinessArchivePayload {
  version: 1
  kind: 'mts.readiness.archive'
  archived_at: string
  operator: string
  note: string
  locale: LocaleCode
  score: ReadinessScoreBreakdown
  doctor: DoctorArchiveSummary
  /** 已完成项 id（稳定、机器可读） */
  checklist: {
    production: string[]
    edgeHttps: string[]
    backupSchedule: string[]
  }
  /** 全量清单条目（title/detail 已按 locale 解析） */
  catalog: {
    production: CatalogItem[]
    edgeHttps: CatalogItem[]
    backupSchedule: CatalogItem[]
  }
  state: ReadinessState
}

const copy = {
  zh: {
    title: '# MTS 可商用就绪演练归档',
    time: '时间',
    operator: '操作者',
    score: '就绪评分',
    parts: '分项',
    checklistPart: '清单',
    backupPart: '备份',
    reasons: '扣分原因',
    note: '备注',
    doctor: '## Doctor',
    notLoaded: '未加载',
    completed: '## 已完成清单',
    catalog: '## 清单明细（本地化）',
    done: '完成',
    open: '未完成',
    footer: '_本文件由 Dashboard 就绪中心生成，不代表生产人工验收已完成。_',
  },
  en: {
    title: '# MTS commercial readiness drill archive',
    time: 'Time',
    operator: 'Operator',
    score: 'Readiness score',
    parts: 'Breakdown',
    checklistPart: 'Checklist',
    backupPart: 'Backup',
    reasons: 'Score deductions',
    note: 'Note',
    doctor: '## Doctor',
    notLoaded: 'Not loaded',
    completed: '## Completed checklist ids',
    catalog: '## Catalog details (localized)',
    done: 'done',
    open: 'open',
    footer: '_Generated by Dashboard readiness center; does not prove production human acceptance is complete._',
  },
} as const

export function buildReadinessArchive(input: ReadinessArchiveInput): ReadinessArchivePayload {
  const archived_at = input.now ?? new Date().toISOString()
  const locale: LocaleCode = input.locale === 'en' ? 'en' : 'zh'
  const productionDone = completedIds(input.state.production).sort()
  const edgeDone = completedIds(input.state.edgeHttps).sort()
  const scheduleDone = completedIds(input.state.backupSchedule).sort()
  return {
    version: 1,
    kind: 'mts.readiness.archive',
    archived_at,
    operator: (input.operator ?? '').trim() || 'unknown',
    note: (input.note ?? '').trim(),
    locale,
    score: { ...input.score, reasons: [...input.score.reasons] },
    doctor: {
      loaded: input.doctor.loaded,
      ok: input.doctor.ok,
      http_tls_enabled: input.doctor.http_tls_enabled ?? null,
      warn_count: input.doctor.warn_count ?? 0,
      checks: (input.doctor.checks ?? []).map((c) => ({ ...c })),
      error: input.doctor.error,
    },
    checklist: {
      production: productionDone,
      edgeHttps: edgeDone,
      backupSchedule: scheduleDone,
    },
    catalog: {
      production: productionCatalog(productionDone, locale),
      edgeHttps: edgeHttpsCatalog(edgeDone, locale),
      backupSchedule: backupScheduleCatalog(scheduleDone, locale),
    },
    state: {
      production: { ...input.state.production },
      edgeHttps: { ...input.state.edgeHttps },
      backupSchedule: { ...input.state.backupSchedule },
      updatedAt: input.state.updatedAt,
    },
  }
}

function formatCatalogSection(
  label: string,
  items: CatalogItem[],
  locale: LocaleCode,
): string[] {
  const t = copy[locale]
  const lines = [`### ${label}`, '']
  for (const item of items) {
    const mark = item.done ? t.done : t.open
    lines.push(`- [${mark}] ${item.id} — ${item.title}`)
    lines.push(`  - ${item.detail}`)
  }
  if (!items.length) lines.push('- —')
  lines.push('')
  return lines
}

export function formatReadinessArchiveMarkdown(a: ReadinessArchivePayload): string {
  const locale: LocaleCode = a.locale === 'en' ? 'en' : 'zh'
  const t = copy[locale]
  const sep = locale === 'zh' ? '：' : ': '
  const lines: string[] = [
    t.title,
    '',
    `- ${t.time}${sep}${a.archived_at}`,
    `- ${t.operator}${sep}${a.operator}`,
    `- ${t.score}${sep}${a.score.total}%`,
    `- ${t.parts}${sep}${t.checklistPart} ${a.score.checklist}% / HTTPS ${a.score.edgeHttps}% / ${t.backupPart} ${a.score.backupSchedule}% / Doctor ${a.score.doctor}%`,
  ]
  if (a.score.reasons.length) {
    lines.push(`- ${t.reasons}${sep}${a.score.reasons.join(', ')}`)
  }
  if (a.note) {
    lines.push(`- ${t.note}${sep}${a.note}`)
  }
  lines.push('', t.doctor, '')
  if (!a.doctor.loaded) {
    lines.push(`- ${t.notLoaded}${a.doctor.error ? `${sep}${a.doctor.error}` : ''}`)
  } else {
    lines.push(`- ok: ${a.doctor.ok === true ? 'yes' : 'no'}`)
    lines.push(`- http_tls_enabled: ${String(a.doctor.http_tls_enabled)}`)
    lines.push(`- warn_count: ${a.doctor.warn_count ?? 0}`)
    for (const c of a.doctor.checks ?? []) {
      lines.push(`- [${c.level}] ${c.code}: ${c.message}`)
    }
  }
  lines.push('', t.completed, '')
  lines.push(`- production: ${a.checklist.production.join(', ') || '—'}`)
  lines.push(`- edgeHttps: ${a.checklist.edgeHttps.join(', ') || '—'}`)
  lines.push(`- backupSchedule: ${a.checklist.backupSchedule.join(', ') || '—'}`)
  lines.push('', t.catalog, '')
  lines.push(...formatCatalogSection('production', a.catalog.production, locale))
  lines.push(...formatCatalogSection('edgeHttps', a.catalog.edgeHttps, locale))
  lines.push(...formatCatalogSection('backupSchedule', a.catalog.backupSchedule, locale))
  lines.push('---', '', t.footer, '')
  return lines.join('\n')
}

export function archiveFilenames(at = new Date()): { json: string; md: string } {
  const stamp = at.toISOString().replace(/[:.]/g, '-').slice(0, 19)
  return {
    json: `mts-readiness-archive-${stamp}.json`,
    md: `mts-readiness-archive-${stamp}.md`,
  }
}
