/** 就绪/演练归档模板（JSON + Markdown），供运维交接下载 */

import type { ReadinessScoreBreakdown } from './readinessScore.ts'
import type { ReadinessState, SignoffNotes } from './readinessState.ts'
import { completedIds, normalizeSignoffNotes } from './readinessState.ts'
import type { LocaleCode } from './localizedText.ts'
import { buildDeployKitSummary, type DeployKitSummary } from './deployTemplates.ts'
import {
  backupScheduleCatalog,
  edgeHttpsCatalog,
  productionCatalog,
  type CatalogItem,
} from './checklistCatalog.ts'
import {
  buildExportPreflight,
  type ExportPreflightItem,
} from './exportPreflight.ts'
import {
  formatDownsampleStatusSummaryLine,
  normalizeDownsampleStatusSummary,
  type DownsampleStatusSummaryInput,
} from './downsampleStatusSummary.ts'
import {
  buildCommercialHandoffSummary,
  formatPasswordPolicyHandoffLine,
  formatSessionCalibrationHandoffLine,
  type CommercialHandoffSummary,
} from './commercialHandoffSummary.ts'

export interface DoctorArchiveSummary {
  loaded: boolean
  ok?: boolean
  http_tls_enabled?: boolean | null
  warn_count?: number
  checks?: { level: string; code: string; message: string }[]
  error?: string
}

export interface ReadinessArchiveInput {
  operator?: string
  note?: string
  state: ReadinessState
  score: ReadinessScoreBreakdown
  doctor: DoctorArchiveSummary
  now?: string
  /** 导出文案语言；默认 zh */
  locale?: LocaleCode
  /** 可选：降采样 statuses 摘要（只读归档） */
  downsample_status_summary?: DownsampleStatusSummaryInput | null
  /** 可选：密码策略 + 会话校准交接摘要 */
  commercial_handoff?: CommercialHandoffSummary | null
  /** 构造会话校准摘要用（未传 commercial_handoff 时） */
  session_expires_at?: string | null
  session_remaining_seconds?: number | null
  session_checked_at_ms?: number | null
  session_server_time_unix?: number | null
}

export interface ReadinessArchivePayload {
  version: 1
  kind: 'mts.readiness.archive'
  archived_at: string
  operator: string
  note: string
  locale: LocaleCode
  score: ReadinessScoreBreakdown
  doctor: DoctorArchiveSummary
  /** 已完成项 id（稳定、机器可读） */
  checklist: {
    production: string[]
    edgeHttps: string[]
    backupSchedule: string[]
  }
  /** 全量清单条目（title/detail 已按 locale 解析） */
  catalog: {
    production: CatalogItem[]
    edgeHttps: CatalogItem[]
    backupSchedule: CatalogItem[]
  }
  state: ReadinessState
  /** 部署材料包索引（与验收包对齐） */
  deploy_kit: DeployKitSummary
  /** 本地提醒勾选 id（不代表部署验收完成） */
  deploy_kit_local_hints: string[]
  /** 部署侧人工签核证据备注（自由文本；不计入评分） */
  signoff_notes: SignoffNotes
  /** 导出前预检摘要（与验收包对齐；不计分） */
  export_preflight: {
    warn_count: number
    info_count: number
    ok_count: number
    items: Pick<ExportPreflightItem, 'id' | 'level' | 'message' | 'target'>[]
  }
  /** 可选：降采样健康摘要（/admin/downsample/statuses summary） */
  downsample_status_summary?: Required<DownsampleStatusSummaryInput> | null
  /** 可选：密码策略与会话校准（可商用交接） */
  commercial_handoff?: CommercialHandoffSummary | null
}

const copy = {
  zh: {
    title: '# MTS 可商用就绪演练归档',
    time: '时间',
    operator: '操作者',
    score: '就绪评分',
    parts: '分项',
    checklistPart: '清单',
    backupPart: '备份',
    reasons: '扣分原因',
    note: '备注',
    doctor: '## Doctor',
    notLoaded: '未加载',
    completed: '## 已完成清单',
    catalog: '## 清单明细（本地化）',
    done: '完成',
    open: '未完成',
    deployKit: '## 部署材料包索引',
    deployKitHints: '本地提醒勾选',
    deployKitManual: '人工签核仍为部署侧必做',
    signoff: '## 部署侧签核证据备注',
    signoffEdge: '边缘证书/HSTS',
    signoffBackup: '异地备份',
    signoffAlert: '备份失败告警',
    signoffEmpty: '（未填写）',
    preflight: '## 导出前预检',
    preflightNotScored: '预检不阻止导出，不代表生产验收完成',
    footer: '_本文件由 Dashboard 就绪中心生成，不代表生产人工验收已完成。_',
  },
  en: {
    title: '# MTS commercial readiness drill archive',
    time: 'Time',
    operator: 'Operator',
    score: 'Readiness score',
    parts: 'Breakdown',
    checklistPart: 'Checklist',
    backupPart: 'Backup',
    reasons: 'Score deductions',
    note: 'Note',
    doctor: '## Doctor',
    notLoaded: 'Not loaded',
    completed: '## Completed checklist ids',
    catalog: '## Catalog details (localized)',
    done: 'done',
    open: 'open',
    deployKit: '## Deployment kit index',
    deployKitHints: 'Local reminder checks',
    deployKitManual: 'Manual sign-off remains deployment-side required',
    signoff: '## Deployment-side sign-off evidence notes',
    signoffEdge: 'Edge cert / HSTS',
    signoffBackup: 'Off-host backup',
    signoffAlert: 'Backup failure alerting',
    signoffEmpty: '(empty)',
    preflight: '## Export preflight',
    preflightNotScored: 'Preflight does not block export or complete acceptance',
    footer: '_Generated by Dashboard readiness center; does not prove production human acceptance is complete._',
  },
} as const

export function buildReadinessArchive(input: ReadinessArchiveInput): ReadinessArchivePayload {
  const archived_at = input.now ?? new Date().toISOString()
  const locale: LocaleCode = input.locale === 'en' ? 'en' : 'zh'
  const productionDone = completedIds(input.state.production).sort()
  const edgeDone = completedIds(input.state.edgeHttps).sort()
  const scheduleDone = completedIds(input.state.backupSchedule).sort()
  return {
    version: 1,
    kind: 'mts.readiness.archive',
    archived_at,
    operator: (input.operator ?? '').trim() || 'unknown',
    note: (input.note ?? '').trim(),
    locale,
    score: { ...input.score, reasons: [...input.score.reasons] },
    doctor: {
      loaded: input.doctor.loaded,
      ok: input.doctor.ok,
      http_tls_enabled: input.doctor.http_tls_enabled ?? null,
      warn_count: input.doctor.warn_count ?? 0,
      checks: (input.doctor.checks ?? []).map((c) => ({ ...c })),
      error: input.doctor.error,
    },
    checklist: {
      production: productionDone,
      edgeHttps: edgeDone,
      backupSchedule: scheduleDone,
    },
    catalog: {
      production: productionCatalog(productionDone, locale),
      edgeHttps: edgeHttpsCatalog(edgeDone, locale),
      backupSchedule: backupScheduleCatalog(scheduleDone, locale),
    },
    state: {
      production: { ...input.state.production },
      edgeHttps: { ...input.state.edgeHttps },
      backupSchedule: { ...input.state.backupSchedule },
      deployKit: { ...(input.state.deployKit ?? {}) },
      signoffNotes: normalizeSignoffNotes(input.state.signoffNotes),
      updatedAt: input.state.updatedAt,
    },
    deploy_kit: buildDeployKitSummary(locale),
    deploy_kit_local_hints: completedIds(input.state.deployKit).sort(),
    signoff_notes: normalizeSignoffNotes(input.state.signoffNotes),
    export_preflight: (() => {
      const pf = buildExportPreflight({
        locale,
        requiredChecklistRatio: (input.score.checklist ?? 0) / 100,
        edgeHttpsRequiredRatio: (input.score.edgeHttps ?? 0) / 100,
        backupScheduleRequiredRatio: (input.score.backupSchedule ?? 0) / 100,
        doctorLoaded: !!input.doctor.loaded,
        doctorOk: input.doctor.ok,
        doctorWarnCount: input.doctor.warn_count,
        httpTlsEnabled: input.doctor.http_tls_enabled ?? null,
        signoffNotes: input.state.signoffNotes,
        deployKitReviewed: !!input.state.deployKit?.reviewed,
      })
      return {
        warn_count: pf.warnCount,
        info_count: pf.infoCount,
        ok_count: pf.okCount,
        items: pf.items.map((i) => ({
          id: i.id,
          level: i.level,
          message: i.message,
          target: i.target,
        })),
      }
    })(),
    downsample_status_summary: input.downsample_status_summary
      ? normalizeDownsampleStatusSummary(input.downsample_status_summary)
      : null,
    commercial_handoff:
      input.commercial_handoff ??
      buildCommercialHandoffSummary({
        expiresAtIso: input.session_expires_at,
        serverRemainingSec: input.session_remaining_seconds,
        checkedAtMs: input.session_checked_at_ms,
        serverTimeUnix: input.session_server_time_unix,
      }),
  }
}

function formatCatalogSection(
  label: string,
  items: CatalogItem[],
  locale: LocaleCode,
): string[] {
  const t = copy[locale]
  const lines = [`### ${label}`, '']
  for (const item of items) {
    const mark = item.done ? t.done : t.open
    lines.push(`- [${mark}] ${item.id} — ${item.title}`)
    lines.push(`  - ${item.detail}`)
  }
  if (!items.length) lines.push('- —')
  lines.push('')
  return lines
}

export function formatReadinessArchiveMarkdown(a: ReadinessArchivePayload): string {
  const locale: LocaleCode = a.locale === 'en' ? 'en' : 'zh'
  const t = copy[locale]
  const sep = locale === 'zh' ? '：' : ': '
  const lines: string[] = [
    t.title,
    '',
    `- ${t.time}${sep}${a.archived_at}`,
    `- ${t.operator}${sep}${a.operator}`,
    `- ${t.score}${sep}${a.score.total}%`,
    `- ${t.parts}${sep}${t.checklistPart} ${a.score.checklist}% / HTTPS ${a.score.edgeHttps}% / ${t.backupPart} ${a.score.backupSchedule}% / Doctor ${a.score.doctor}%`,
  ]
  if (a.score.reasons.length) {
    lines.push(`- ${t.reasons}${sep}${a.score.reasons.join(', ')}`)
  }
  if (a.note) {
    lines.push(`- ${t.note}${sep}${a.note}`)
  }
  lines.push('', t.doctor, '')
  if (!a.doctor.loaded) {
    lines.push(`- ${t.notLoaded}${a.doctor.error ? `${sep}${a.doctor.error}` : ''}`)
  } else {
    lines.push(`- ok: ${a.doctor.ok === true ? 'yes' : 'no'}`)
    lines.push(`- http_tls_enabled: ${String(a.doctor.http_tls_enabled)}`)
    lines.push(`- warn_count: ${a.doctor.warn_count ?? 0}`)
    for (const c of a.doctor.checks ?? []) {
      lines.push(`- [${c.level}] ${c.code}: ${c.message}`)
    }
  }
  if (a.downsample_status_summary) {
    lines.push('', '## Downsample status summary', '')
    lines.push(`- ${formatDownsampleStatusSummaryLine(a.downsample_status_summary)}`)
  }
  if (a.commercial_handoff) {
    lines.push('', '## Commercial handoff', '')
    lines.push(`- password_policy: ${formatPasswordPolicyHandoffLine(a.commercial_handoff.password_policy)}`)
    lines.push(
      `- session_calibration: ${formatSessionCalibrationHandoffLine(a.commercial_handoff.session_calibration)}`,
    )
  }
  lines.push('', t.completed, '')
  lines.push(`- production: ${a.checklist.production.join(', ') || '—'}`)
  lines.push(`- edgeHttps: ${a.checklist.edgeHttps.join(', ') || '—'}`)
  lines.push(`- backupSchedule: ${a.checklist.backupSchedule.join(', ') || '—'}`)
  lines.push('', t.catalog, '')
  lines.push(...formatCatalogSection('production', a.catalog.production, locale))
  lines.push(...formatCatalogSection('edgeHttps', a.catalog.edgeHttps, locale))
  lines.push(...formatCatalogSection('backupSchedule', a.catalog.backupSchedule, locale))
  lines.push(t.deployKit, '')
  lines.push(`- count: ${a.deploy_kit.count}`)
  lines.push(`- ${t.deployKitManual}`)
  lines.push(`- note: ${a.deploy_kit.note}`)
  for (const item of a.deploy_kit.items) {
    lines.push(`- ${item.id} — ${item.title} (\`${item.filename}\`)`)
  }
  lines.push(
    `- ${t.deployKitHints}: ${a.deploy_kit_local_hints.join(', ') || '—'}`,
  )
  lines.push('', t.signoff, '')
  lines.push(`- ${t.signoffEdge}${sep}${a.signoff_notes.edgeHttps || t.signoffEmpty}`)
  lines.push(`- ${t.signoffBackup}${sep}${a.signoff_notes.backupOffsite || t.signoffEmpty}`)
  lines.push(`- ${t.signoffAlert}${sep}${a.signoff_notes.backupAlert || t.signoffEmpty}`)
  lines.push('', t.preflight, '')
  lines.push(
    `- ok: ${a.export_preflight.ok_count} · warn: ${a.export_preflight.warn_count} · info: ${a.export_preflight.info_count}`,
  )
  for (const item of a.export_preflight.items.filter((x) => x.level !== 'ok' || x.id === 'footer').slice(0, 12)) {
    lines.push(`- [${item.level}] ${item.id}: ${item.message}`)
  }
  lines.push(`- ${t.preflightNotScored}`)
  lines.push('', '---', '', t.footer, '')
  return lines.join('\n')
}

export function archiveFilenames(at = new Date()): { json: string; md: string } {
  const stamp = at.toISOString().replace(/[:.]/g, '-').slice(0, 19)
  return {
    json: `mts-readiness-archive-${stamp}.json`,
    md: `mts-readiness-archive-${stamp}.md`,
  }
}
