import { expect, test, type Page } from '@playwright/test'

const NEW_PASSWORD = 'AdminChanged!2026'

async function login(page: Page, user: string, password: string) {
  await page.goto('/login')
  await expect(page.getByTestId('login-panel')).toBeVisible()
  await page.getByTestId('login-username').fill(user)
  await page.getByTestId('login-password').fill(password)
  await page.getByTestId('login-submit').click()
}

test.describe.configure({ mode: 'serial' })

test('commercial browser smoke path', async ({ page }) => {
  // 0) 登录表单校验：空密码 -> alert 错误区
  await page.goto('/login')
  await expect(page.getByTestId('login-toggle-password')).toBeVisible()
  await expect(page.getByTestId('login-remember-user')).toBeVisible()
  await page.getByTestId('login-username').fill('admin')
  await page.getByTestId('login-password').fill('')
  await page.getByTestId('login-submit').click()
  await expect(page.getByTestId('login-error')).toBeVisible()
  await expect(page.getByTestId('login-error')).toHaveAttribute('role', 'alert')
  await expect(page.getByTestId('login-password')).toHaveAttribute('aria-invalid', 'true')
  await expect(page.getByTestId('login-ttl')).toBeVisible()

  // 1) bootstrap 默认密码 -> 强制改密
  await login(page, 'admin', 'admin')
  await expect(page).toHaveURL(/force-change-password/)
  await expect(page.getByTestId('password-hints')).toBeVisible()
  await page.getByTestId('force-old').fill('admin')
  await page.getByTestId('force-new').fill(NEW_PASSWORD)
  await page.getByTestId('force-confirm').fill(NEW_PASSWORD)
  await page.getByTestId('force-password-submit').click()
  await expect(page).toHaveURL(/login/)
  await expect(page.getByText(/密码已更新|new password/i)).toBeVisible()

  // 2) 新密码登录
  await login(page, 'admin', NEW_PASSWORD)
  await expect(page).not.toHaveURL(/login|force-change/)
  await expect(page.getByText(/概览|健康|Healthy|Ready/i).first()).toBeVisible()
  await expect(page.getByTestId('overview-page')).toBeVisible()
  await expect(page.getByTestId('overview-summary')).toBeVisible()
  await expect(page.getByTestId('sidebar')).toBeVisible()
  await expect(page.getByTestId('sidebar-collapse-toggle')).toBeVisible()
  await expect(page.getByTestId('sidebar-section-workspace')).toBeVisible()
  await expect(page.getByTestId('sidebar-section-label-workspace')).toBeVisible()
  // 组内排序控件（工作区至少 3 项）
  await expect(page.getByTestId('sidebar-order-up-query')).toBeVisible()
  await expect(page.getByTestId('sidebar-order-down-query')).toBeVisible()
  await page.getByTestId('sidebar-order-up-query').click()
  // 过滤时隐藏排序（避免与搜索结果冲突）
  await page.getByTestId('sidebar-filter').fill('query')
  await expect(page.getByTestId('sidebar-order-up-query')).toHaveCount(0)
  await page.getByTestId('sidebar-filter-clear').click()
  await expect(page.getByTestId('sidebar-order-up-query')).toBeVisible()
  await expect(page.getByTestId('overview-export-json')).toBeVisible()
  await expect(page.getByTestId('overview-copy-snapshot')).toBeVisible()
  await expect(page.getByTestId('offline-banner')).toHaveCount(0)
  await expect(page.getByTestId('server-unreachable-banner')).toHaveCount(0)
  await expect(page.getByTestId('overview-connectivity')).toBeVisible()
  await expect(page.getByTestId('overview-connectivity-kind')).toBeVisible()
  await expect(page.getByTestId('topbar-account')).toBeVisible()
  await expect(page.getByTestId('topbar-connectivity')).toBeVisible()

  // account session card
  await page.goto('/account')
  await expect(page.getByTestId('account-session')).toBeVisible()
  await expect(page.getByTestId('account-session-remaining')).toBeVisible()
  await page.goto('/')
  await expect(page.getByTestId('skip-to-main')).toHaveCount(1)
  await expect(page).toHaveTitle(/仪表盘|概览|Overview/)

  // 3) Line Protocol 写入
  await page.goto('/write')
  await expect(page.getByTestId('write-page')).toBeVisible()
  await expect(page.getByTestId('write-export-draft')).toBeVisible()
  await expect(page.getByTestId('write-export-result')).toBeVisible()
  await page.getByRole('main').getByRole('button', { name: 'Line Protocol' }).click()
  await page.getByRole('main').locator('textarea').first().fill('cpu,host=e2e-playwright usage=0.42 1000')
  await page.getByTestId('write-submit').click()
  await expect(page.getByTestId('write-result-ok')).toBeVisible({ timeout: 20_000 })
  await expect(page.getByRole('main').getByText(/写入成功/).first()).toBeVisible({ timeout: 20_000 })
  await expect(page.getByRole('main').getByRole('button', { name: /表单写入|Form write/i })).toBeVisible()
  await expect(page.getByTestId('write-mode-tabs')).toBeVisible()
  await expect(page.getByTestId('write-mode-typed')).toBeVisible()
  await expect(page.getByTestId('write-prefs-hint')).toBeVisible()

  // 4) 查询页可达 + 表单标签 i18n
  await page.goto('/query')
  await expect(page.getByTestId('query-page')).toBeVisible()
  await expect(page.getByTestId('breadcrumb-bar')).toBeVisible()
  await expect(page.getByTestId('breadcrumb-current')).toBeVisible()
  await expect(page.getByTestId('breadcrumb-copy-path')).toBeVisible()
  await expect(page.getByRole('main').getByText(/查询|Query/i).first()).toBeVisible()
  await expect(page.getByRole('main').getByText(/数据库|Database/).first()).toBeVisible()
  await expect(page.getByRole('main').getByText(/开始时间|Start/).first()).toBeVisible()
  await expect(page.getByTestId('query-export-csv')).toBeVisible()

  // 5) 运维 Flush（确认按钮文案为「执行」）
  await page.goto('/operations')
  await expect(page.getByTestId('ops-page')).toBeVisible()
  await expect(page.getByRole('main').getByRole('heading', { name: /^(运维|Operations)$/ })).toBeVisible()
  await expect(page.getByTestId('ops-export-stats')).toBeVisible()
  await expect(page.getByTestId('ops-copy-stats')).toBeVisible()
  await expect(page.getByTestId('ops-flush')).toContainText(/Flush/)
  await expect(page.getByTestId('ops-retention')).toContainText(/保留策略|Retention/i)
  await page.getByRole('main').getByRole('button', { name: /Flush/ }).first().click()
  await page.getByRole('button', { name: '执行', exact: true }).click()
  await expect(page.getByRole('main').getByText('Flush 已完成').first()).toBeVisible({ timeout: 20_000 })

  // 6) 权限矩阵 / 实时授权 / 指标
  await page.goto('/access')
  await expect(page.getByTestId('access-matrix-page')).toBeVisible()
  await expect(page.getByRole('main').getByRole('heading', { name: /权限能力矩阵|Capability matrix/ })).toBeVisible()
  // a11y 树中 th 可能暴露为 cell
  await expect(page.getByRole('main').getByText(/管理员|Admin/).first()).toBeVisible()
  await expect(page.getByTestId('access-matrix-export')).toBeVisible()
  await page.goto('/access/grants')
  await expect(page.getByTestId('access-grants-page')).toBeVisible()
  await expect(page.getByRole('main').getByRole('heading', { name: /实时授权|Live grants/ })).toBeVisible()
  await expect(page.getByTestId('access-grants-export-json')).toBeVisible()
  await expect(page.getByTestId('access-grants-export-csv')).toBeVisible()
  await page.goto('/api-spec')
  await expect(page.getByTestId('api-spec-page')).toBeVisible()
  await expect(page.getByTestId('api-spec-export-json')).toBeVisible()
  await expect(page.getByTestId('api-spec-export-md')).toBeVisible()
  await page.goto('/observability/metrics')
  await expect(page.getByTestId('metrics-page')).toBeVisible()
  await expect(page.getByTestId('metrics-filter')).toBeVisible()
  await expect(page.getByTestId('metrics-export-raw')).toBeVisible()
  await expect(page.getByTestId('metrics-auto-refresh')).toBeVisible()
  await expect(page.getByRole('main').getByRole('heading', { name: /指标浏览|Metrics explorer/ })).toBeVisible()
  await expect(page.getByRole('main').getByText(/指标族|Families|样本|Samples/i).first()).toBeVisible()

  // 6b) 库/用户/降采样清单导出
  await page.goto('/databases')
  await expect(page.getByTestId('databases-page')).toBeVisible()
  await expect(page.getByTestId('databases-export-json')).toBeVisible()
  await expect(page.getByTestId('databases-export-csv')).toBeVisible()
  await page.goto('/users')
  await expect(page.getByTestId('users-page')).toBeVisible()
  await expect(page.getByTestId('users-export-json')).toBeVisible()
  await expect(page.getByTestId('users-export-csv')).toBeVisible()
  await page.goto('/downsample')
  await expect(page.getByTestId('downsample-page')).toBeVisible()
  await expect(page.getByTestId('downsample-export-json')).toBeVisible()
  await expect(page.getByTestId('downsample-export-csv')).toBeVisible()

  // 7) 存储与 data-snapshot 入口
  await page.goto('/storage')
  await expect(page.getByTestId('storage-page')).toBeVisible()
  await expect(page.getByTestId('storage-export-fetch')).toBeVisible()
  await expect(page.getByTestId('storage-drill-source')).toBeVisible()
  await expect(page.getByTestId('storage-drill-source-select')).toBeVisible()
  await expect(page.getByRole('main').getByRole('heading', { name: /^(存储|Storage)$/ })).toBeVisible()
  await expect(page.getByTestId('storage-data-snapshot')).toBeVisible()

  // Config 表头 i18n（表头在空数据时仍可见；a11y 树中 th 可能暴露为 cell）
  await page.goto('/config')
  await expect(page.getByTestId('config-page')).toBeVisible()
  await expect(page.getByTestId('config-export-effective')).toBeVisible()
  await expect(page.getByTestId('config-copy-effective')).toBeVisible()
  await expect(page.getByTestId('config-export-schema')).toBeVisible()
  await expect(page.getByTestId('config-export-error-codes')).toBeVisible()
  await expect(page.getByRole('main').getByRole('heading', { level: 1, name: /^(配置|Config)$/ })).toBeVisible()
  await expect(page.getByTestId('config-schema-table').getByText(/^(名称|Name)$/)).toBeVisible()
  await expect(page.getByTestId('config-error-codes-table').getByText(/^(错误码|Code)$/)).toBeVisible()

  // 8) 就绪中心：勾选持久化 + 导出/归档入口
  await page.goto('/ops/readiness')
  await expect(page.getByRole('main').getByRole('heading', { name: /就绪中心|Commercial readiness|可商用就绪/ })).toBeVisible()
  const firstCheckbox = page.locator('[data-testid^="readiness-prod-"]').first()
  await firstCheckbox.check()
  await expect(firstCheckbox).toBeChecked()
  await page.reload()
  await expect(page.locator('[data-testid^="readiness-prod-"]').first()).toBeChecked()
  await expect(page.getByTestId('readiness-export-preflight')).toBeVisible()
  await expect(page.getByTestId('readiness-preflight-summary')).toBeVisible()
  await expect(page.getByTestId('readiness-copy-preflight')).toBeVisible()
  await expect(page.getByTestId('readiness-next-steps')).toBeVisible()
  await expect(page.locator('[data-testid^="next-step-"]').first()).toBeVisible()
  await expect(page.getByTestId('readiness-doctor-panel')).toBeVisible()
  await expect(page.getByTestId('preflight-item-signoff')).toBeVisible()
  await expect(page.getByTestId('preflight-jump-signoff')).toBeVisible()
  await page.getByTestId('preflight-jump-signoff').click()
  await expect(page.getByTestId('readiness-signoff-notes')).toBeVisible()
  await expect(page.getByTestId('preflight-jump-deployKit')).toBeVisible()
  await page.getByTestId('preflight-jump-deployKit').click()
  await expect(page.getByTestId('readiness-deploy-kit')).toBeVisible()
  await expect(page.getByTestId('deploy-acceptance-boundary')).toBeVisible()
  await expect(page.getByTestId('deploy-runbook-drill')).toBeVisible()
  await expect(page.getByTestId('deploy-drill-download')).toBeVisible()
  await expect(page.getByTestId('deploy-drill-step-edge-cert-present')).toBeVisible()
  await expect(page.getByTestId('deploy-runbook-links')).toBeVisible()
  await expect(page.getByTestId('deploy-accept-step-1')).toBeVisible()
  await expect(page.getByTestId('readiness-export')).toBeVisible()
  await expect(page.getByTestId('readiness-archive')).toBeVisible()
  await expect(page.getByTestId('readiness-acceptance-pack')).toBeVisible()
  await expect(page.getByTestId('readiness-deploy-kit')).toBeVisible()
  await expect(page.getByTestId('deploy-kit-local-hints')).toBeVisible()
  await expect(page.getByTestId('deploy-kit-hint-reviewed')).toBeVisible()
  await expect(page.getByTestId('readiness-deploy-kit-download')).toBeVisible()
  await expect(page.getByTestId('readiness-signoff-notes')).toBeVisible()
  await expect(page.getByTestId('signoff-completeness')).toBeVisible()
  await expect(page.getByTestId('signoff-edge-https')).toBeVisible()
  await expect(page.getByTestId('signoff-backup-offsite')).toBeVisible()
  await expect(page.getByTestId('deploy-tpl-rsync-offsite')).toBeVisible()
  await expect(page.getByTestId('deploy-tpl-backup-alert-hook')).toBeVisible()
  await expect(page.getByTestId('deploy-tpl-nginx-https')).toBeVisible()
  await expect(page.getByTestId('deploy-tpl-cron-backup')).toBeVisible()
  await expect(page.getByTestId('deploy-copy-nginx-https')).toBeVisible()

  // 就绪清单数据层双语（生产清单标题）
  await expect(page.getByRole('main').getByText('边缘 HTTPS / TLS').first()).toBeVisible()
  const localeBtnReadiness = page.locator('header button').filter({ has: page.locator('.sr-only', { hasText: /^(zh|en)$/ }) })
  await localeBtnReadiness.click()
  await expect(page.getByRole('main').getByText('Edge HTTPS / TLS').first()).toBeVisible()
  await localeBtnReadiness.click()

  // 9) About 页
  await page.goto('/about')
  await expect(page.getByRole('main').getByText(/关于|About/i).first()).toBeVisible()
  await expect(page.getByRole('main').getByText(/mts-dashboard/i).first()).toBeVisible()

  // 10) 账户页改密入口 + 会话徽章
  await page.goto('/account')
  await expect(page.getByTestId('account-password-form')).toBeVisible()
  await expect(page.getByTestId('account-landing-select')).toBeVisible()
  await expect(page.getByTestId('account-density-select')).toBeVisible()
  await expect(page.getByTestId('account-prefs-tools')).toBeVisible()
  await expect(page.getByTestId('account-prefs-export')).toBeVisible()
  await expect(page.getByTestId('account-prefs-copy')).toBeVisible()
  await expect(page.getByTestId('account-prefs-reset')).toBeVisible()
  await expect(page.getByTestId('account-prefs-import-submit')).toBeVisible()
  // P98：偏好导出/重置应覆盖侧栏导航排序（本机 localStorage）
  const navKey = 'mts.dashboard.nav-order.prefs.v1'
  const orderBefore = await page.evaluate((k) => localStorage.getItem(k), navKey)
  expect(orderBefore).toBeTruthy()
  await page.getByTestId('account-prefs-reset').click()
  await expect.poll(async () => page.evaluate((k) => localStorage.getItem(k), navKey)).toBeNull()
  await page.getByTestId('account-density-select').selectOption('compact')
  await expect(page.locator('html')).toHaveAttribute('data-density', 'compact')
  await page.getByTestId('account-density-select').selectOption('comfortable')
  await expect(page.locator('html')).not.toHaveAttribute('data-density', 'compact')
  await expect(page.getByTestId('session-badge')).toBeVisible()

  // 11) 命令面板跳转 + 快捷键帮助 + 最近访问
  await expect(page.getByTestId('topbar-shortcuts')).toBeVisible()
  await expect(page.getByTestId('topbar-notify-history')).toBeVisible()
  await page.getByTestId('topbar-shortcuts').click()
  await expect(page.getByTestId('shortcuts-help')).toBeVisible()
  await page.getByTestId('shortcuts-help-close').click()
  await page.keyboard.press('Control+KeyK')
  await expect(page.getByTestId('command-palette')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('command-palette')).toHaveCount(0)
  await expect(page.getByTestId('recent-routes')).toBeVisible()
  // 侧栏导航过滤（展开态）
  await expect(page.getByTestId('sidebar-filter')).toBeVisible()
  await page.getByTestId('sidebar-filter').fill('audit')
  await expect(page.getByTestId('sidebar-nav-audit')).toBeVisible()
  await expect(page.getByTestId('sidebar-nav-home')).toHaveCount(0)
  await page.getByTestId('sidebar-filter-clear').click()
  await expect(page.getByTestId('sidebar-nav-home')).toBeVisible()
  // / 聚焦侧栏过滤（非输入态；先 blur 输入框）
  await page.locator('#main-content').focus()
  await page.keyboard.press('/')
  await expect(page.getByTestId('sidebar-filter')).toBeFocused()
  // 命令面板跳转（在清空最近访问前，避免额外 goto 干扰）
  await page.getByTestId('topbar-command-palette').click()
  await expect(page.getByTestId('command-palette')).toBeVisible()
  await expect(page.getByTestId('command-palette-recent-label')).toBeVisible()
  await page.getByTestId('command-palette-input').fill('audit')
  await expect(page.getByTestId('command-item-audit')).toBeVisible()
  await page.getByTestId('command-item-audit').click()
  await expect(page).toHaveURL(/\/audit/)
  await expect(page.getByTestId('audit-quick-ranges')).toBeVisible()
  await expect(page.getByTestId('audit-export-json')).toBeVisible()
  await expect(page.getByTestId('audit-export-csv')).toBeVisible()
  await expect(page.getByTestId('audit-limit')).toBeVisible()
  await expect(page.getByTestId('audit-merged-hint')).toBeVisible()

  // 命令面板运维深链：签核备注 / 部署材料
  await page.getByTestId('topbar-command-palette').click()
  await expect(page.getByTestId('command-palette')).toBeVisible()
  await page.getByTestId('command-palette-input').fill('signoff')
  await page.getByTestId('command-item-readiness-signoff').click()
  await expect(page).toHaveURL(/ops\/readiness/)
  await expect(page.getByTestId('readiness-signoff-notes')).toBeVisible()
  await page.getByTestId('topbar-command-palette').click()
  await page.getByTestId('command-palette-input').fill('deploy kit')
  await page.getByTestId('command-item-readiness-deploy-kit').click()
  await expect(page).toHaveURL(/ops\/readiness/)
  await expect(page.getByTestId('readiness-deploy-kit')).toBeVisible()

  // 最近访问清空：多页后 clear，仅剩当前页（>1 才显示清空）
  await page.goto('/write')
  await page.goto('/query')
  await expect(page.getByTestId('recent-routes')).toBeVisible()
  await expect(page.getByTestId('recent-routes-clear')).toBeVisible()
  await page.getByTestId('recent-routes-clear').click()
  await expect(page.getByTestId('recent-routes-clear')).toHaveCount(0)

  // 固定最近访问
  await page.goto('/write')
  await page.goto('/query')
  await expect(page.getByTestId('recent-route-pin-/write')).toBeVisible()
  await page.getByTestId('recent-route-pin-/write').click()
  await expect(page.getByTestId('recent-route-pin-/write')).toHaveAttribute('aria-pressed', 'true')
  // 命令面板最近访问展示固定
  await page.getByTestId('topbar-command-palette').click()
  await expect(page.getByTestId('command-palette')).toBeVisible()
  await expect(page.getByTestId('command-recent-/write')).toHaveAttribute('data-pinned', 'true')
  await page.keyboard.press('Escape')

  // 通知历史面板 + 导出入口 + 快捷键
  await page.getByTestId('topbar-notify-history').click()
  await expect(page.getByTestId('notify-history-panel')).toBeVisible()
  await expect(page.getByTestId('notify-history-export-json')).toBeVisible()
  await expect(page.getByTestId('notify-history-export-csv')).toBeVisible()
  await expect(page.getByTestId('notify-history-copy')).toBeVisible()
  await expect(page.getByTestId('notify-history-filter')).toBeVisible()
  await expect(page.getByTestId('notify-history-search')).toBeVisible()
  await expect(page.getByTestId('notify-history-time-range')).toBeVisible()
  await expect(page.getByTestId('notify-history-since')).toBeVisible()
  await expect(page.getByTestId('notify-history-until')).toBeVisible()
  await page.getByTestId('notify-history-filter').selectOption('error')
  await page.getByTestId('notify-history-search').fill('x')
  await page.getByTestId('notify-history-time-range').selectOption('24h')
  await page.getByTestId('notify-history-time-clear').click()
  await expect(page.getByTestId('notify-history-time-range')).toHaveValue('all')
  await page.getByTestId('notify-history-search').fill('')
  await page.getByTestId('notify-history-filter').selectOption('all')
  await page.getByTestId('notify-history-close').click()
  await expect(page.getByTestId('notify-history-panel')).toHaveCount(0)
  await page.locator('#main-content').focus()
  await page.keyboard.press('Control+Shift+KeyH')
  await expect(page.getByTestId('notify-history-panel')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('notify-history-panel')).toHaveCount(0)

  // 12) 跳过链接 + 运维操作历史导出入口
  await page.goto('/operations')
  await expect(page.getByTestId('ops-action-log')).toBeVisible()
  await expect(page.getByTestId('ops-export-log')).toBeVisible()
  await expect(page.getByTestId('ops-export-stats')).toBeVisible()
  await expect(page.getByTestId('ops-copy-stats')).toBeVisible()
  await expect(page.getByTestId('ops-export-maint-errors')).toBeVisible()
  await expect(page.getByTestId('ops-copy-maint-errors')).toBeVisible()
  await page.locator('[data-testid="skip-to-main"]').evaluate((el: HTMLElement) => el.focus())
  await expect(page.getByTestId('skip-to-main')).toBeFocused()

  // 13) 用户/数据库筛选入口
  await page.goto('/users')
  await expect(page.getByTestId('users-filter')).toBeVisible()
  await expect(page.getByTestId('users-role-filter')).toBeVisible()
  await expect(page.getByTestId('users-role-filter')).toContainText(/管理员|Admin|普通用户|User/)
  await page.goto('/databases')
  await expect(page.getByTestId('databases-filter')).toBeVisible()
  await expect(page.getByRole('main').getByRole('heading', { name: /数据库|Databases/i })).toBeVisible()

  // 14) 降采样筛选/批量/状态/区间操作入口
  await page.goto('/downsample')
  await expect(page.getByTestId('downsample-filter-bar')).toBeVisible()
  await expect(page.getByTestId('downsample-filter')).toBeVisible()
  await expect(page.getByTestId('downsample-batch-enable')).toBeVisible()
  await expect(page.getByTestId('downsample-status-panel')).toBeVisible()

  // 15) Overview 就绪评分入口
  await page.goto('/')
  await expect(page.getByTestId('overview-readiness-score')).toBeVisible()
  await expect(page.getByTestId('overview-readiness-total')).toBeVisible()
  await expect(page.getByTestId('overview-go-deploy-kit')).toBeVisible()
  await expect(page.getByTestId('overview-signoff-completeness')).toBeVisible()
  await expect(page.getByTestId('overview-go-signoff')).toBeVisible()
  await expect(page.getByTestId('overview-export-preflight')).toBeVisible()
  await expect(page.getByTestId('overview-next-steps')).toBeVisible()
  await expect(page.locator('[data-testid^="overview-next-step-"]').first()).toBeVisible()
  await expect(page.getByTestId('overview-go-preflight')).toBeVisible()
  await page.getByTestId('overview-go-preflight').click()
  await expect(page).toHaveURL(/ops\/readiness/)
  await expect(page.getByTestId('readiness-export-preflight')).toBeVisible()
  await page.goto('/')
  await expect(page.getByTestId('overview-go-signoff')).toBeVisible()
  await page.getByTestId('overview-go-signoff').click()
  await expect(page).toHaveURL(/ops\/readiness/)
  await expect(page.getByTestId('readiness-signoff-notes')).toBeVisible()
  await page.goto('/')
  await expect(page.getByTestId('overview-go-deploy-kit')).toBeVisible()
  await page.getByTestId('overview-go-deploy-kit').click()
  await expect(page).toHaveURL(/ops\/readiness/)
  await expect(page.getByTestId('readiness-deploy-kit')).toBeVisible()
  await page.goto('/')
  await page.getByTestId('overview-go-readiness').click()
  await expect(page).toHaveURL(/ops\/readiness/)


  // 键盘可达：命令面板 + 快捷键帮助 + skip-link 聚焦主内容
  await page.goto('/')
  await page.keyboard.press('Control+k')
  await expect(page.getByTestId('command-palette')).toBeVisible()
  await expect(page.getByTestId('command-palette-input')).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('command-palette')).toHaveCount(0)
  await page.getByTestId('topbar-shortcuts').click()
  await expect(page.getByTestId('shortcuts-help')).toBeVisible()
  await page.getByTestId('shortcuts-help-close').click()
  await expect(page.getByTestId('shortcuts-help')).toHaveCount(0)
  await page.getByTestId('skip-to-main').focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('#main-content')).toBeFocused()

  // 账户页改密表单可达
  await page.goto('/account')
  await expect(page.getByTestId('account-page')).toBeVisible()
  await expect(page.getByTestId('account-export-json')).toBeVisible()
  await expect(page.getByTestId('account-copy-snapshot')).toBeVisible()
  await expect(page.getByTestId('account-password-form')).toBeVisible()
  await expect(page.getByTestId('password-hints')).toBeVisible()
  await page.getByTestId('account-password-submit').click()
  await expect(page.getByTestId('account-password-error')).toBeVisible()
  await expect(page.getByTestId('account-old-password')).toHaveAttribute('aria-invalid', 'true')

  // About 字段标签
  await page.goto('/about')
  await expect(page.getByTestId('about-page')).toBeVisible()
  await expect(page.getByTestId('about-export-json')).toBeVisible()
  await expect(page.getByTestId('about-copy')).toBeVisible()
  await expect(page.getByRole('main').getByText(/BASE_URL|API/).first()).toBeVisible()

  // 16) 权限矩阵 / 实时授权 / 指标 / 404（含矩阵行双语）
  await page.goto('/access')
  await expect(page.getByTestId('access-matrix-page')).toBeVisible()
  await expect(page.getByTestId('access-matrix-export')).toBeEnabled()
  await expect(page.getByRole('main').getByRole('heading', { name: /权限能力矩阵|Capability matrix/ })).toBeVisible()
  // 使用 table cell，避免命中 select 中隐藏的 option
  await expect(page.getByRole('main').getByRole('cell', { name: '数据面' }).first()).toBeVisible()
  await expect(page.getByRole('main').getByRole('cell', { name: /查询 rows/i }).first()).toBeVisible()
  // 切换语言后 capability 行与区域标签应为英文
  const localeBtn = page.locator('header button').filter({ has: page.locator('.sr-only', { hasText: /^(zh|en)$/ }) })
  await localeBtn.click()
  await expect(page.getByRole('main').getByRole('heading', { name: /Capability matrix/ })).toBeVisible()
  await expect(page.getByRole('main').getByRole('cell', { name: 'Data plane' }).first()).toBeVisible()
  await expect(page.getByRole('main').getByRole('cell', { name: /Query rows\/columns\/stream\/explain/i }).first()).toBeVisible()
  await expect(page.getByRole('main').getByRole('cell', { name: /Non-admin needs read grant/i }).first()).toBeVisible()
  // 切回中文，避免后续步骤依赖中文文案
  await localeBtn.click()
  await expect(page.getByRole('main').getByRole('heading', { name: /权限能力矩阵/ })).toBeVisible()
  await page.goto('/access/grants')
  await expect(page.getByTestId('access-grants-page')).toBeVisible()
  await expect(page.getByRole('main').getByRole('heading', { name: /实时授权|Live grants/ })).toBeVisible()
  await expect(page.getByTestId('access-grants-export-json')).toBeVisible()
  await page.goto('/api-spec')
  await expect(page.getByTestId('api-spec-page')).toBeVisible()
  await expect(page.getByTestId('api-spec-title')).toBeVisible()
  await expect(page.getByTestId('api-spec-export-json')).toBeVisible()
  await page.goto('/observability/metrics')
  await expect(page.getByRole('main').getByRole('heading', { name: /指标浏览|Metrics explorer/ })).toBeVisible()
  await page.goto('/this-route-should-404')
  await expect(page.getByTestId('not-found-page')).toBeVisible()
  await expect(page.getByTestId('not-found-go-overview')).toBeVisible()
  await expect(page.getByText(/页面不存在|Page not found|404/).first()).toBeVisible()
})
